<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\View;

class SetLanguage
{
    public function handle(Request $request, Closure $next)
    {
        $lang = Session::get('lang', 'en');
        App::setLocale($lang);

        $translations = [
            'en' => [
                'dashboard' => 'Dashboard',
                'clients' => 'Clients',
                'transactions' => 'Transactions',
                'exchange_rates' => 'Exchange Rates',
                'reports' => 'Reports',
                'users' => 'Users',
                'logout' => 'Logout',
                'main_branch' => 'Main Branch',
                'welcome_back' => 'Welcome back',
                'total_clients' => 'Total Clients',
                'total_usd' => 'Total USD',
                'total_iqd' => 'Total IQD',
                'total_eur' => 'Total EUR',
                'total_try' => 'Total TRY',
                'todays_deposits' => "Today's Deposits",
                'todays_withdrawals' => "Today's Withdrawals",
                'recent_transactions' => 'Recent Transactions',
                'no_transactions' => 'No transactions yet',
                'add_client' => 'Add Client',
                'client_code' => 'Client Code',
                'full_name' => 'Full Name',
                'full_name_ar' => 'Full Name (Arabic)',
                'phone' => 'Phone',
                'address' => 'Address',
                'national_id' => 'National ID',
                'status' => 'Status',
                'active' => 'Active',
                'inactive' => 'Inactive',
                'action' => 'Action',
                'view' => 'View',
                'search_clients' => 'Search by name, code or phone...',
                'total_clients_count' => 'total clients',
                'cancel' => 'Cancel',
                'save' => 'Save',
                'member_since' => 'Member Since',
                'client_info' => 'Client Info',
                'current_rates' => 'Current Rates',
                'back' => 'Back',
                'print_statement' => 'Print Statement',
                'add_transaction' => 'Add Transaction',
                'portal_access' => 'Portal Access',
                'portal_enabled' => 'Client portal is enabled',
                'enable_portal' => 'Enable Client Portal Access',
                'disable_portal' => 'Disable Portal Access',
                'set_password' => 'Set Password',
                'enable_access' => 'Enable Portal Access',
                'date' => 'Date',
                'type' => 'Type',
                'currency' => 'Currency',
                'amount' => 'Amount',
                'original' => 'Original',
                'before' => 'Before',
                'after' => 'After',
                'notes' => 'Notes',
                'cashier' => 'Cashier',
                'sender' => 'Sender',
                'deposit' => 'Deposit',
                'withdrawal' => 'Withdrawal',
                'all' => 'All',
                'sender_name' => 'Sender Name (optional)',
                'sender_phone' => 'Sender Phone (optional)',
                'notes_optional' => 'Notes (optional)',
                'confirm_save' => 'Confirm & Save',
                'equivalent' => 'Equivalent in USD',
                'transaction_history' => 'Transaction History',
                'set_new_rate' => 'Set New Rate',
                'from' => 'From',
                'to' => 'To',
                'rate' => 'Rate',
                'set_by' => 'Set By',
                'save_rate' => 'Save Rate',
                'set_daily_rates' => 'Set daily rates manually',
                'add_user' => 'Add User',
                'email' => 'Email',
                'password' => 'Password',
                'role' => 'Role',
                'system_users' => 'system users',
                'admin' => 'Admin',
                'name' => 'Name',
                'usd_balance' => 'USD Balance',
                'iqd_balance' => 'IQD Balance',
                'eur_balance' => 'EUR Balance',
                'try_balance' => 'TRY Balance',
                'owes_company' => 'Owes company',
                'zero_balance' => 'Zero balance',
                'has_funds' => 'Has funds',
            ],
            'ar' => [
                'dashboard' => 'الرئيسية',
                'clients' => 'العملاء',
                'transactions' => 'المعاملات',
                'exchange_rates' => 'أسعار الصرف',
                'reports' => 'التقارير',
                'users' => 'المستخدمون',
                'logout' => 'تسجيل الخروج',
                'main_branch' => 'الفرع الرئيسي',
                'welcome_back' => 'مرحباً بعودتك',
                'total_clients' => 'إجمالي العملاء',
                'total_usd' => 'إجمالي الدولار',
                'total_iqd' => 'إجمالي الدينار',
                'total_eur' => 'إجمالي اليورو',
                'total_try' => 'إجمالي الليرة',
                'todays_deposits' => 'إيداعات اليوم',
                'todays_withdrawals' => 'سحوبات اليوم',
                'recent_transactions' => 'المعاملات الأخيرة',
                'no_transactions' => 'لا توجد معاملات بعد',
                'add_client' => 'إضافة عميل',
                'client_code' => 'رمز العميل',
                'full_name' => 'الاسم الكامل',
                'full_name_ar' => 'الاسم بالعربي',
                'phone' => 'الهاتف',
                'address' => 'العنوان',
                'national_id' => 'الهوية الوطنية',
                'status' => 'الحالة',
                'active' => 'نشط',
                'inactive' => 'غير نشط',
                'action' => 'إجراء',
                'view' => 'عرض',
                'search_clients' => 'البحث بالاسم أو الرمز أو الهاتف',
                'total_clients_count' => 'إجمالي العملاء',
                'cancel' => 'إلغاء',
                'save' => 'حفظ',
                'member_since' => 'عضو منذ',
                'client_info' => 'معلومات العميل',
                'current_rates' => 'الأسعار الحالية',
                'back' => 'رجوع',
                'print_statement' => 'طباعة الكشف',
                'add_transaction' => 'إضافة معاملة',
                'portal_access' => 'صلاحية البوابة',
                'portal_enabled' => 'بوابة العميل مفعلة',
                'enable_portal' => 'تفعيل بوابة العميل',
                'disable_portal' => 'تعطيل البوابة',
                'set_password' => 'تعيين كلمة المرور',
                'enable_access' => 'تفعيل الوصول',
                'date' => 'التاريخ',
                'type' => 'النوع',
                'currency' => 'العملة',
                'amount' => 'المبلغ',
                'original' => 'الأصلي',
                'before' => 'قبل',
                'after' => 'بعد',
                'notes' => 'ملاحظات',
                'cashier' => 'الصراف',
                'sender' => 'المرسل',
                'deposit' => 'إيداع',
                'withdrawal' => 'سحب',
                'all' => 'الكل',
                'sender_name' => 'اسم المرسل',
                'sender_phone' => 'هاتف المرسل',
                'notes_optional' => 'ملاحظات اختيارية',
                'confirm_save' => 'تأكيد وحفظ',
                'equivalent' => 'المعادل بالدولار',
                'transaction_history' => 'سجل المعاملات',
                'set_new_rate' => 'تعيين سعر جديد',
                'from' => 'من',
                'to' => 'إلى',
                'rate' => 'السعر',
                'set_by' => 'بواسطة',
                'save_rate' => 'حفظ السعر',
                'set_daily_rates' => 'تعيين الأسعار اليومية',
                'add_user' => 'إضافة مستخدم',
                'email' => 'البريد الإلكتروني',
                'password' => 'كلمة المرور',
                'role' => 'الدور',
                'system_users' => 'مستخدمو النظام',
                'admin' => 'مدير',
                'name' => 'الاسم',
                'usd_balance' => 'رصيد الدولار',
                'iqd_balance' => 'رصيد الدينار',
                'eur_balance' => 'رصيد اليورو',
                'try_balance' => 'رصيد الليرة',
                'owes_company' => 'مديون للشركة',
                'zero_balance' => 'رصيد صفر',
                'has_funds' => 'لديه رصيد',
            ],
        ];

        View::share('trans', $translations[$lang]);
        View::share('currentLang', $lang);
        View::share('isRTL', $lang === 'ar');

        return $next($request);
    }
}